title: Codewind
email: codewind-dev@eclipse.org
description: Eclipse Codewind
keywords: Eclipse, docker, container, devops, applications, development, iteration, microservices, cloud, services, rapid, integrated
baseurl: "/codewind"
future: true
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
exclude: [node_modules]
collections:
  documentations:
    output: true
  news:
    output: true
  newsarchive:
    output: true
  blog:
    output: true
  guides:
    output: true